# mainブランチをマージしたら、releaseタグを切って、npm run buildさせてchrome extensionsをzip化する
name: Release on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive dist directory
        run: zip -r adjustimer.zip dist

      - name: Get version from manifest.json
        id: manifest
        run: echo "VERSION=$(jq -r .version manifest.json)" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: adjustimer.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}